name: Python Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Replace 'x' with your desired Python version (e.g., 3.6, 3.7, 3.8, etc.)

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt upgrade -y
        sudo apt install postgresql build-essential python3-pillow python3-lxml python3-dev python3-pip python3-setuptools npm nodejs git gdebi libldap2-dev libsasl2-dev libxml2-dev python3-wheel python3-venv libxslt1-dev node-less libjpeg-dev -y
        
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any requirements, specify them in 'requirements.txt'
        pip install pytest
      
    - name: Run Tests
      run: pytest  # This assumes you have a pytest configuration in your project
